# Start up the Kafka image and specify a constant PLAINTEXT port to use in our scripts.
services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  pyscript:
    build: . # Build this project to interact with our kafka

